//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2P {
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Brossom : global::System.Configuration.ApplicationSettingsBase {
        
        private static Brossom defaultInstance = ((Brossom)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Brossom())));        
        public  static Brossom Default {
            get {return defaultInstance;}
        }
    }
}
